/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.content.security.policy.internal.servlet.filter;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.content.security.policy.ContentSecurityPolicyNonceProviderUtil;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.util.ContentTypes;
import com.liferay.portal.kernel.util.HtmlUtil;
import com.liferay.portal.kernel.util.PortalRunMode;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.security.content.security.policy.internal.ContentSecurityPolicyNonceManager;
import com.liferay.portal.servlet.filters.BasePortalFilter;

import java.io.PrintWriter;

import java.util.Objects;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;

/**
 * This filters looks for content that has not been adapted to CSP in any HTML
 * output generated by the Portal.
 *
 * It is only enabled when the Portal is started in test mode.
 *
 * @author Iván Zaera Avellón
 * @review
 */
@Component(
	property = {
		"after-filter=Content Security Policy Filter", "dispatcher=FORWARD",
		"dispatcher=REQUEST", "servlet-context-name=",
		"servlet-filter-name=Content Security Policy Test Filter",
		"url-pattern=/*"
	},
	service = Filter.class
)
public class ContentSecurityPolicyTestFilter extends BasePortalFilter {

	@Override
	public boolean isFilterEnabled() {
		return PortalRunMode.isTestMode();
	}

	@Override
	protected void processFilter(
			HttpServletRequest httpServletRequest,
			HttpServletResponse httpServletResponse, FilterChain filterChain)
		throws Exception {

		boolean cleanUpNonce = false;

		String nonce = _contentSecurityPolicyNonceManager.getNonce(
			httpServletRequest);

		if (Validator.isNull(nonce)) {
			nonce = _contentSecurityPolicyNonceManager.setTestNonce(
				httpServletRequest);

			cleanUpNonce = true;
		}

		PrintWriter printWriter = httpServletResponse.getWriter();

		ContentSecurityPolicyHttpServletResponse
			contentSecurityPolicyHttpServletResponse =
				new ContentSecurityPolicyHttpServletResponse(
					httpServletResponse);

		filterChain.doFilter(
			httpServletRequest, contentSecurityPolicyHttpServletResponse);

		String contentType =
			contentSecurityPolicyHttpServletResponse.getContentType();
		String content = contentSecurityPolicyHttpServletResponse.getContent();

		try {
			if ((contentType != null) &&
				contentType.contains(ContentTypes.TEXT_HTML)) {

				Document document = Jsoup.parse(content);

				for (Element element : document.getAllElements()) {
					_checkElement(nonce, element);
				}
			}

			printWriter.write(content);

			printWriter.close();

			httpServletResponse.setContentLength(content.length());
		}
		catch (Exception exception) {
			_log.error(exception);

			printWriter.write("<html><head><title>Content Security Policy ");
			printWriter.write("Check Failure</title></head><body><style ");
			printWriter.write(
				ContentSecurityPolicyNonceProviderUtil.getNonceAttribute(
					httpServletRequest));
			printWriter.write(">pre{margin:4em auto; max-width:1024px;");
			printWriter.write("overflow:hidden;text-wrap:auto;} pre div{");
			printWriter.write("background:lightgray;display:inline-block;");
			printWriter.write("margin-bottom:2em;padding:.2em 1em;}</style>");
			printWriter.write("<pre><center><div>Content ");
			printWriter.write("Security Policy Check Failure</div></center>");
			printWriter.write(HtmlUtil.escape(exception.getMessage()));
			printWriter.write("</pre></body></html>");
		}
		finally {
			if (cleanUpNonce) {
				_contentSecurityPolicyNonceManager.cleanUpNonce(
					httpServletRequest);
			}
		}
	}

	protected static final String[] FORBIDDEN_ATTRIBUTES = {
		"onafterprint", "onbeforeprint", "onbeforematch", "onbeforetoggle",
		"onbeforeunload", "onblur", "oncancel", "onchange", "onclick",
		"onconnect", "oncontextlost", "oncontextrestored",
		"oncurrententrychange", "ondispose", "onerror", "onfocus", "onformdata",
		"onhashchange", "oninput", "oninvalid", "onlanguagechange", "onload",
		"onmessage", "onmessageerror", "onnavigate", "onnavigateerror",
		"onnavigatesuccess", "onoffline", "ononline", "onopen", "onpageswap",
		"onpagehide", "onpagereveal", "onpageshow", "onpointercancel",
		"onpopstate", "onreadystatechange", "onreset", "onselect", "onstorage",
		"onsubmit", "ontoggle", "onunhandledrejection", "onunload",
		"onvisibilitychange"
	};

	private void _checkElement(String expectedNonce, Element element) {
		StringBundler sb = new StringBundler();

		String name = StringUtil.toLowerCase(element.tagName());
		Attributes attributes = element.attributes();

		if ((name.equals("link") &&
			 Objects.equals(attributes.get("rel"), "stylesheet")) ||
			name.equals("script") || name.equals("style")) {

			String nonce = attributes.get("nonce");

			if ((nonce == null) || !Objects.equals(nonce, expectedNonce)) {
				sb.append("Generated HTML contains a <");
				sb.append(name);
				sb.append("> tag without a CSP nonce.\n\nPlease check your ");
				sb.append("changes to the source code and make sure you ");
				sb.append("always use <aui:");
				sb.append(name);
				sb.append("> tag in JSP and template files or ");
				sb.append("CSPNonceProviderUtil in Java files.\n\nThe ");
				sb.append("failing code and context follows:\n\n");
			}
		}
		else {
			for (String forbiddenAttribute : FORBIDDEN_ATTRIBUTES) {
				if (attributes.hasKeyIgnoreCase(forbiddenAttribute)) {
					sb.append("Generated HTML has a node containing the '");
					sb.append(forbiddenAttribute);
					sb.append("' attribute.\n\nPlease check your changes to ");
					sb.append("the source code and make sure do not use the '");
					sb.append(forbiddenAttribute);
					sb.append("' attribute in any Java, JSP, or template ");
					sb.append("file.\n\nThe failing code and context ");
					sb.append("follows:\n\n");
				}
			}
		}

		if (sb.length() > 0) {
			Element previousElementSibling = element.previousElementSibling();
			Element nextElementSibling = element.nextElementSibling();

			if ((previousElementSibling == null) &&
				(nextElementSibling == null)) {

				Element parent = element.parent();

				sb.append(
					(parent == null) ? element.outerHtml() :
						parent.outerHtml());
			}
			else {
				if (previousElementSibling != null) {
					sb.append(previousElementSibling.outerHtml());
				}

				sb.append(element.outerHtml());

				if (nextElementSibling != null) {
					sb.append(nextElementSibling.outerHtml());
				}
			}

			throw new IllegalStateException(sb.toString());
		}
	}

	private static final Log _log = LogFactoryUtil.getLog(
		ContentSecurityPolicyTestFilter.class);

	@Reference
	private ContentSecurityPolicyNonceManager
		_contentSecurityPolicyNonceManager;

}