/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

module.exports = {
	build: {
		report: false,
		bundler: {
			ignore: [
				"__liferay__/**/*"
			],
			exclude: {
				'*': true,
			},
		},
		exports: [
			'@clayui/alert',
			'@clayui/autocomplete',
			'@clayui/badge',
			'@clayui/breadcrumb',
			'@clayui/button',
			'@clayui/card',
			'@clayui/charts',
			'@clayui/color-picker',
			'@clayui/core',
			'@clayui/css',
			'@clayui/data-provider',
			'@clayui/date-picker',
			'@clayui/drop-down',
			'@clayui/empty-state',
			'@clayui/form',
			'@clayui/icon',
			'@clayui/label',
			'@clayui/layout',
			'@clayui/link',
			'@clayui/list',
			'@clayui/loading-indicator',
			'@clayui/localized-input',
			'@clayui/management-toolbar',
			'@clayui/modal',
			'@clayui/multi-select',
			'@clayui/multi-step-nav',
			'@clayui/nav',
			'@clayui/navigation-bar',
			'@clayui/pagination',
			'@clayui/pagination-bar',
			'@clayui/panel',
			'@clayui/popover',
			'@clayui/progress-bar',
			{ package: '@clayui/provider', rewriteExports: true },
			'@clayui/shared',
			'@clayui/slider',
			'@clayui/sticker',
			'@clayui/table',
			'@clayui/tabs',
			'@clayui/time-picker',
			'@clayui/toolbar',
			'@clayui/tooltip',
			'@clayui/upper-toolbar',
			'clay-alert',
			'clay-autocomplete',
			'clay-badge',
			'clay-button',
			'clay-card',
			'clay-card-grid',
			'clay-checkbox',
			'clay-collapse',
			'clay-component',
			'clay-css',
			'clay-data-provider',
			'clay-dataset-display',
			'clay-dropdown',
			'clay-icon',
			'clay-label',
			'clay-link',
			'clay-list',
			'clay-loading-indicator',
			'clay-modal',
			'clay-multi-select',
			'clay-navigation-bar',
			'clay-pagination',
			'clay-pagination-bar',
			'clay-portal',
			'clay-progress-bar',
			'clay-radio',
			'clay-select',
			'clay-sticker',
			'clay-table',
			'clay-tooltip',
		],
		imports: {
			'frontend-js-react-web': [
				'react-dom',
				'prop-types',
				'react-dnd',
				'formik',
				'react',
				'react-dnd-html5-backend',
				'classnames',
			],
			'frontend-taglib-clay': [
				'@clayui/alert',
				'@clayui/autocomplete',
				'@clayui/badge',
				'@clayui/breadcrumb',
				'@clayui/button',
				'@clayui/card',
				'@clayui/charts',
				'@clayui/color-picker',
				'@clayui/core',
				'@clayui/css',
				'@clayui/data-provider',
				'@clayui/date-picker',
				'@clayui/drop-down',
				'@clayui/empty-state',
				'@clayui/form',
				'@clayui/icon',
				'@clayui/label',
				'@clayui/layout',
				'@clayui/link',
				'@clayui/list',
				'@clayui/loading-indicator',
				'@clayui/localized-input',
				'@clayui/management-toolbar',
				'@clayui/modal',
				'@clayui/multi-select',
				'@clayui/multi-step-nav',
				'@clayui/nav',
				'@clayui/navigation-bar',
				'@clayui/pagination',
				'@clayui/pagination-bar',
				'@clayui/panel',
				'@clayui/popover',
				'@clayui/progress-bar',
				'@clayui/provider',
				'@clayui/shared',
				'@clayui/slider',
				'@clayui/sticker',
				'@clayui/table',
				'@clayui/tabs',
				'@clayui/time-picker',
				'@clayui/toolbar',
				'@clayui/tooltip',
				'@clayui/upper-toolbar',
				'clay-alert',
				'clay-autocomplete',
				'clay-badge',
				'clay-button',
				'clay-card',
				'clay-card-grid',
				'clay-checkbox',
				'clay-collapse',
				'clay-component',
				'clay-css',
				'clay-data-provider',
				'clay-dataset-display',
				'clay-dropdown',
				'clay-icon',
				'clay-label',
				'clay-link',
				'clay-list',
				'clay-loading-indicator',
				'clay-modal',
				'clay-multi-select',
				'clay-navigation-bar',
				'clay-pagination',
				'clay-pagination-bar',
				'clay-portal',
				'clay-progress-bar',
				'clay-radio',
				'clay-select',
				'clay-sticker',
				'clay-table',
				'clay-tooltip',
			],
		},
	},
};
