##
## Test Suites
##

    modified.files.includes[relevant][oauth2-provider-java-rule]=\
        **/*.java,\
        **/test/**,\
        **/testIntegration/**

    relevant.rule.names=oauth2-provider-java-rule

    test.batch.names[relevant][oauth2-provider-java-rule]=\
        modules-integration-mysql57,\
        modules-unit

    #
    # Portal Hotfix Release
    #

    test.batch.run.property.query[functional-tomcat-mysql*-jdk*][test-portal-hotfix-release]=\
        (portal.acceptance == true) AND \
        (\
            (testray.component.names ~ "OAuth 2") OR \
            (testray.main.component.name ~ "OAuth 2")\
        )

    #
    # Relevant
    #

    modules.includes.required.test.batch.class.names.includes[modules-integration-mysql57][relevant][oauth2-provider-java-rule]=\
        apps/oauth2-provider/**/*Test.java

    modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][oauth2-provider-java-rule]=\
        apps/oauth2-provider/**/*Test.java

##
## Testray
##

    testray.main.component.name=OAuth 2